### ISSUE TITLE
test_empty_uvdata

### ISSUE THREAD

**Issue by steven-murray** [HERA-Team/hera_sim#18]
Tests are giving the following error on one test:

```
======================================================================
ERROR: test_empty_uvdata (test_io.TestIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/HERA-Team/hera_sim/hera_sim/tests/test_io.py", line 20, in test_empty_uvdata
    uvd = io.empty_uvdata(nfreqs, ntimes, ants=ants, antpairs=antpairs1)
  File "/home/travis/build/HERA-Team/hera_sim/hera_sim/io.py", line 84, in empty_uvdata
    sim_lsts = get_lst_for_time(sim_times, lat, lon, alt)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/pyuvdata/utils.py", line 459, in get_lst_for_time
    jd, jd_array, atol=1e-6, rtol=1e-12))] = t.sidereal_time('apparent').radian
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/astropy/time/core.py", line 758, in sidereal_time
    gst = self._erfa_sidereal_time(available_models[model.upper()])
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/astropy/time/core.py", line 774, in _erfa_sidereal_time
    for jd_part in ('jd1', 'jd2')]
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/astropy/time/core.py", line 1125, in __getattr__
    tm._set_scale(attr)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/astropy/time/core.py", line 496, in _set_scale
    args.append(get_dt(jd1, jd2))
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/astropy/time/core.py", line 1247, in _get_delta_ut1_utc
    delta = iers_table.ut1_utc(jd1, jd2)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/astropy/utils/iers/iers.py", line 229, in ut1_utc
    self.ut1_utc_source if return_status else None)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/astropy/utils/iers/iers.py", line 327, in _interpolate
    self._check_interpolate_indices(i1, i, np.max(mjd))
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/astropy/utils/iers/iers.py", line 270, in _check_interpolate_indices
    raise IERSRangeError('(some) times are outside of range covered '
IERSRangeError: (some) times are outside of range covered by IERS table.
```

Clearly this test passed previously. I don't know if the test is dependent on the time or something, but if so it will need to be fixed.

**Comment by steven-murray** [comment]
this seems to be fixed now, probably in upstream library.
