### ISSUE TITLE
Antenna naming in pyuvsim_wrapper can cause error

### ISSUE THREAD

**Issue by hughbg** [HERA-Team/hera_sim#241]
I have a new conda environment with the latest packages installed. I run a very simple sim:

```
data_model = ModelData.from_config("hera_sim.yaml")
simulator = UVSim()
psimulation = VisibilitySimulation(data_model=data_model, simulator=simulator)
psimulation.simulate()
```

I got an error:
```
Traceback (most recent call last):
  File "/users/hgarsden/paper_runs/run.py", line 63, in <module>
    psimulation.simulate()
  File "/users/hgarsden/miniconda3/envs/tests/lib/python3.10/site-packages/hera_sim/visibilities/simulators.py", line 334, in simulate
    vis = self.simulator.simulate(self.data_model)
  File "/users/hgarsden/miniconda3/envs/tests/lib/python3.10/site-packages/hera_sim/visibilities/pyuvsim_wrapper.py", line 25, in simulate
    beam_dict = {
  File "/users/hgarsden/miniconda3/envs/tests/lib/python3.10/site-packages/hera_sim/visibilities/pyuvsim_wrapper.py", line 26, in <dictcomp>
    ant: data_model.beam_ids[str(idx)]
KeyError: '0'
```

The beam ids are indexed by antenna name, and in this simulation the antenna names are like "ANT2", not numbers. I fixed the error by changing the line above to
```
ant: data_model.beam_ids[ant]
```

**Comment by hughbg** [comment]
Covered in #191, can close as duplicate.
